### PR TITLE
Migration to Swift 5 and adapting to iOS 13

### PR DESCRIPTION
**Pull request by philips77**
New features:
* Swift 5
* Support for iOS 13
   - Dark Theme
   - Privacy: Bluetooth Always Usage Description
* Improved UX in Files tab

Bug fixed:
* Compilation error caused by #34 fixed

### CODE REVIEW

**Comment by philips77** [comment]
### Dark Theme
Scanner Device Manager Device Firmware Update Image Manager Files Manager Logs & Stats
